### ISSUE TITLE
Restore the site

### ISSUE THREAD

**Issue by Kaligule** [knowsuchagency/knowsuchagency.github.io.old#1]
Currently the blog is not accessable under  http://journalpanic.com (or elsewhere as far as I could find). It shows this site instead:

<img width="1440" alt="Screenshot 2019-11-29 at 21 14 25" src="https://user-images.githubusercontent.com/3586246/69888646-42790d00-12ed-11ea-811c-fbc47145a0ef.png">

It would be cool to have it available again, at least at knowsuchagency.github.io (which is a redirect currently).

**Comment by knowsuchagency** [comment]
Hey, thanks for the interest and for submitting an issue about it!

Yeah, some squatter stole my old domain out from under me and it's taken me forever to get my blog back in order, but it's back now.

The site itself is https://knowsuchagency.com and the repository for it is https://github.com/knowsuchagency/knowsuchagency.github.io

Thanks again @Kaligule!
